[workspace]

members = [
    "r1-1",
    "r1-2",
    "r1-2-1", 
    "r1-2-2", 
    "r1-2-3",
    "r2-2-1",
    "r2-2-2",
    "r2-2-3",
    "r3-3-1",
    "r3-3-2",
    "r3-3-3",
    "r4",
    "r5",
    "r6",
    "r7",
    "r8",
    "r9",
    "r10",
]

